/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapa;



/**
 *
 * @author pedrotty
 */
public class TelaCalculo extends javax.swing.JFrame {
    static double part = 200;
    static double ipsm = 124.49;
    static double uni = 84;
    static double casu = 128.61;
    static double plano = 703;
    static String resultado;
    static String detalhes;
    

    public static String getDetalhes() {
        return detalhes;
    }

    public static void setDetalhes(String detalhes) {
        TelaCalculo.detalhes = detalhes;
    }
    
    public static String getResultado() {
        return resultado;
    }

    public static void setResultado(String resultado) {
        TelaCalculo.resultado = resultado;
    }
   
    public static double getPart() {
        return part;
    }

    public static void setPart(double part) {
        TelaCalculo.part = part;
    }

    public static double getIpsm() {
        return ipsm;
    }

    public static void setIpsm(double ipsm) {
        TelaCalculo.ipsm = ipsm;
    }

    public static double getUni() {
        return uni;
    }

    public static void setUni(double uni) {
        TelaCalculo.uni = uni;
    }

    public static double getCasu() {
        return casu;
    }

    public static void setCasu(double casu) {
        TelaCalculo.casu = casu;
    }

    public static double getPlano() {
        return plano;
    }

    public static void setPlano(double plano) {
        TelaCalculo.plano = plano;
    }
    
    
    
    

    /**
     * Creates new form NewJFrame
     */
    public TelaCalculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        numpart = new javax.swing.JSpinner();
        numipsm = new javax.swing.JSpinner();
        numunimed = new javax.swing.JSpinner();
        numcasu = new javax.swing.JSpinner();
        numplano = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        valorCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        precopart = new javax.swing.JLabel();
        precocasu = new javax.swing.JLabel();
        precoplano = new javax.swing.JLabel();
        precoipsm = new javax.swing.JLabel();
        precounimed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numpart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numpartPropertyChange(evt);
            }
        });

        jLabel1.setText("Particulares:");

        jLabel2.setText("IPSM:");

        jLabel3.setText("UNIMED");

        jLabel4.setText("CASU");

        jLabel5.setText("Meses do Plano");

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        valorCheck.setText("Mudar valores?");
        valorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCheckActionPerformed(evt);
            }
        });

        jLabel6.setText("Valores padrão:");

        jLabel7.setText("Part:");

        jLabel8.setText("IPSM: ");

        jLabel9.setText("CASU:");

        jLabel10.setText("UNIMED:");

        jLabel11.setText("Plano: ");

        precopart.setText("jLabel12");

        precocasu.setText("jLabel13");

        precoplano.setText("jLabel14");

        precoipsm.setText("jLabel15");

        precounimed.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Calcular))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numpart, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(numipsm)
                            .addComponent(numunimed)
                            .addComponent(numcasu)
                            .addComponent(numplano)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoplano))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precopart))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precocasu)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precounimed))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoipsm)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorCheck)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precopart)
                    .addComponent(precoipsm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(precocasu)
                    .addComponent(precounimed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(precoplano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numipsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numunimed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numcasu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numplano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Calcular)
                .addContainerGap())
        );

        precopart.setText(String.valueOf(getPart()));
        precocasu.setText(String.valueOf(getCasu()));
        precoplano.setText(String.valueOf(getPlano()));
        precoipsm.setText(String.valueOf(getIpsm()));
        precounimed.setText(String.valueOf(getUni()));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        
        int qtdPART = (Integer) numpart.getValue();
        int qtdIPSM = (Integer) numipsm.getValue();
        int qtdUNI = (Integer) numunimed.getValue();
        int qtdCASU = (Integer) numcasu.getValue();
        int qtdMESES = (Integer) numplano.getValue();
        CalculaValor( qtdPART, qtdIPSM, qtdUNI, qtdCASU, qtdMESES);
        
        TelaResultadoDefault obj = new TelaResultadoDefault();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_CalcularActionPerformed

    private void numpartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numpartPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_numpartPropertyChange

    private void valorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCheckActionPerformed
        // TODO add your handling code here:
        if (valorCheck.isSelected()){
        TelaInput obj = new TelaInput();
        obj.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_valorCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner numcasu;
    private javax.swing.JSpinner numipsm;
    private javax.swing.JSpinner numpart;
    private javax.swing.JSpinner numplano;
    private javax.swing.JSpinner numunimed;
    private javax.swing.JLabel precocasu;
    private javax.swing.JLabel precoipsm;
    private javax.swing.JLabel precopart;
    private javax.swing.JLabel precoplano;
    private javax.swing.JLabel precounimed;
    private javax.swing.JCheckBox valorCheck;
    // End of variables declaration//GEN-END:variables


    
    private void CalculaValor(int qtdPART, int qtdIPSM, int qtdUNI, int qtdCASU, int qtdMESES) {
        
        
        double totalFer = qtdIPSM*ipsm + qtdUNI*uni + qtdCASU*casu; //total de $ com fernando
        double totalEdu = qtdPART*part; //total de $ com eduardo
        double totalPlan = qtdMESES*plano; //total de $ do plano
        double totalImp = totalFer*0.275;
        double totalGer = totalFer + totalEdu; //total de $ com os 2
        double finalEdu = totalGer/2 - totalPlan - totalImp/2; //total de $ que deve ficar com eduardo depois da divisão e descontando o plano + impostos
        double finalFer = totalGer/2 + totalPlan + totalImp/2; //total de $ que deve ficar com fernando depois da divisão e adicionando o plano + impostos
        
        
        setDetalhes("--> VALOR COM EDUARDO:\n"
                + qtdPART +" Particulares. Total: "+ totalEdu+"\n ----------------- \n"
                + "--> VALOR COM FERNANDO:\n\n"
                + qtdIPSM+" IPSM. Total: "+ (int) Math.ceil(qtdIPSM*ipsm) +";\n"
                + qtdUNI +" UNIMED. Total:  "+ (int) Math.ceil(qtdUNI*uni) +";\n"
                + qtdCASU +" CASU. Total: "+ (int) Math.ceil(qtdCASU*casu) +".\n\n"
                + "Total: " + (int) Math.ceil(totalFer) + ".\n\nImpostos: "+ (int) Math.ceil(totalImp) +" ("+ (int) Math.ceil(totalImp/2) +" pra cada)\n"
                + "-----------------\n"
                + "VALOR TOTAL: \n"+(int) Math.ceil(totalGer)+ " ("+ (int) Math.ceil(totalGer/2) +" pra cada)\n\n"
                + "VALOR DO PLANO: \n"
                + qtdMESES+" mes(es) ("+totalPlan+")\n\n"
                + "-----------------\n"
                + "Valor final de Eduardo = Parte de Eduardo ("+ (int) Math.ceil(totalGer/2) + ") "
                + " - plano de saúde ("+ totalPlan +") - impostos ("+ (int) Math.ceil(totalImp/2) +") = " + ((int) Math.ceil(finalEdu)) + "\n"
                + "         Diferença: " + ((int) Math.ceil(finalEdu - totalEdu)) + "\n"
                + "Valor final de Fernando = Parte de Fernando: ("+ (int) Math.ceil(totalGer/2) + ") "
                + " + plano de saúde ("+ totalPlan +") + impostos ("+ (int) Math.ceil(totalImp/2) +") = " + ((int) Math.ceil(finalFer)) + "\n"
                + "         Diferença: " + ((int) Math.ceil(finalFer - totalFer)) + "\n");
             
        
        if (finalEdu - totalEdu < 0){ //se o valor que ele deve ficar for menor do que o que tá com ele, ele tem que passar a diferença pra fernando
            setResultado("Particulares: "+ qtdPART+ "\n"
                + "IPSM: "+ qtdIPSM+ "\n"
                + "UNIMED: "+ qtdUNI+ "\n"
                + "Casu: "+ qtdCASU+ "\n"
                + "Meses do plano de saúde: "+ qtdMESES+ "\n\n"
                + "Valor a ser  passado pra Fernando: " + ((int) Math.ceil(finalEdu-totalEdu))*-1);
            return;
        }
        if (finalEdu - totalEdu > 0){ //se o valor que ele deve ficar for maior do que o que tá com ele, fernando tem que passar a diferença pra ele
            setResultado("Particulares: "+ qtdPART+ "\n"
                + "IPSM: "+ qtdIPSM+ "\n"
                + "UNIMED: "+ qtdUNI+ "\n"
                + "Casu: "+ qtdCASU+ "\n"
                + "Meses do plano de saúde: "+ qtdMESES+ "\n\n"
                + "Valor a ser  passado pra Eduardo: " + ((int) Math.ceil(finalEdu-totalEdu)));
            return;
        }
        else {
            setResultado("Particulares: "+ qtdPART+ "\n"
                + "IPSM: "+ qtdIPSM+ "\n"
                + "UNIMED: "+ qtdUNI+ "\n"
                + "Casu: "+ qtdCASU+ "\n"
                + "Meses do plano de saúde: "+ qtdMESES+ "\n\n"
                + "Nenhum valor deve ser passado");
            return;
        }
    }
}
