/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapa;



/**
 *
 * @author pedrotty
 */
public class TelaInput extends javax.swing.JFrame {

    /**
     * Creates new form TelaInput
     */
    public TelaInput() {
        initComponents();
    }
    
    static double part;
    static double ipsm;
    static double uni;
    static double casu;
    static double plano;
    static String resultado;
    static String detalhes;

    public static String getDetalhes() {
        return detalhes;
    }

    public static void setDetalhes(String detalhes) {
        TelaInput.detalhes = detalhes;
    }
    
    public static String getResultado() {
        return resultado;
    }

    public static void setResultado(String resultado) {
        TelaInput.resultado = resultado;
    }

    public static double getPart() {
        return part;
    }

    public static void setPart(double part) {
        TelaInput.part = part;
    }

    public static double getIpsm() {
        return ipsm;
    }

    public static void setIpsm(double ipsm) {
        TelaInput.ipsm = ipsm;
    }

    public static double getUni() {
        return uni;
    }

    public static void setUni(double uni) {
        TelaInput.uni = uni;
    }

    public static double getCasu() {
        return casu;
    }

    public static void setCasu(double casu) {
        TelaInput.casu = casu;
    }

    public static double getPlano() {
        return plano;
    }

    public static void setPlano(double plano) {
        TelaInput.plano = plano;
    }
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numpart = new javax.swing.JSpinner();
        numipsm = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numunimed = new javax.swing.JSpinner();
        numcasu = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numplano = new javax.swing.JSpinner();
        Calcular = new javax.swing.JButton();
        precoPart = new java.awt.TextField();
        precoIPSM = new java.awt.TextField();
        precoUNIMED = new java.awt.TextField();
        precoCASU = new java.awt.TextField();
        precoPlano = new java.awt.TextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Insira valores (+ enter):");

        jLabel10.setText("UNIMED:");

        jLabel8.setText("IPSM: ");

        jLabel7.setText("Part:");

        jLabel9.setText("CASU:");

        jLabel11.setText("Plano: ");

        jLabel1.setText("Particulares:");

        numpart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numpartPropertyChange(evt);
            }
        });

        jLabel2.setText("IPSM:");

        jLabel3.setText("UNIMED");

        jLabel4.setText("CASU");

        jLabel5.setText("Meses do Plano");

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        precoPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoPartActionPerformed(evt);
            }
        });

        precoIPSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoIPSMActionPerformed(evt);
            }
        });

        precoUNIMED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoUNIMEDActionPerformed(evt);
            }
        });

        precoCASU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoCASUActionPerformed(evt);
            }
        });

        precoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoPlanoActionPerformed(evt);
            }
        });

        jButton1.setText("Valores default");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(precoPart, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                            .addComponent(precoCASU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(precoPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(precoIPSM, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                            .addComponent(precoUNIMED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(60, 60, 60)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numipsm, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(numpart)
                                    .addComponent(numunimed)
                                    .addComponent(numcasu)
                                    .addComponent(numplano))))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(Calcular)
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(precoIPSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(precoPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(precoCASU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoUNIMED, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(precoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numipsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numunimed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numcasu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numplano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numpartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numpartPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_numpartPropertyChange

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
 
        int qtdPART = (Integer) numpart.getValue();
        int qtdIPSM = (Integer) numipsm.getValue();
        int qtdUNI = (Integer) numunimed.getValue();
        int qtdCASU = (Integer) numcasu.getValue();
        int qtdMESES = (Integer) numplano.getValue();
        CalculaValor( qtdPART, qtdIPSM, qtdUNI, qtdCASU, qtdMESES);
        
        System.out.println(resultado);
        
        TelaResultadoInput obj = new TelaResultadoInput();
        obj.setVisible(true);
        dispose();
    
    }//GEN-LAST:event_CalcularActionPerformed

    private void precoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoPlanoActionPerformed
        // TODO add your handling code here:
        setPlano(Double.parseDouble(precoPlano.getText()));
        numpart.requestFocus();
    }//GEN-LAST:event_precoPlanoActionPerformed

    private void precoCASUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoCASUActionPerformed
        // TODO add your handling code here:
        setCasu(Double.parseDouble(precoCASU.getText()));
        precoUNIMED.requestFocus();
    }//GEN-LAST:event_precoCASUActionPerformed

    private void precoPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoPartActionPerformed
           // TODO add your handling code here:
        setPart(Double.parseDouble(precoPart.getText()));
        precoIPSM.requestFocus();
        
    }//GEN-LAST:event_precoPartActionPerformed

    private void precoUNIMEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoUNIMEDActionPerformed
        // TODO add your handling code here:
        setUni(Double.parseDouble(precoUNIMED.getText()));
        precoPlano.requestFocus();
    }//GEN-LAST:event_precoUNIMEDActionPerformed

    private void precoIPSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoIPSMActionPerformed
        // TODO add your handling code here:
        setIpsm(Double.parseDouble(precoIPSM.getText()));
        precoCASU.requestFocus();
    }//GEN-LAST:event_precoIPSMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaCalculo obj = new TelaCalculo();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner numcasu;
    private javax.swing.JSpinner numipsm;
    private javax.swing.JSpinner numpart;
    private javax.swing.JSpinner numplano;
    private javax.swing.JSpinner numunimed;
    private java.awt.TextField precoCASU;
    private java.awt.TextField precoIPSM;
    private java.awt.TextField precoPart;
    private java.awt.TextField precoPlano;
    private java.awt.TextField precoUNIMED;
    // End of variables declaration//GEN-END:variables
 private void CalculaValor(int qtdPART, int qtdIPSM, int qtdUNI, int qtdCASU, int qtdMESES) {
        
        
        double totalFer = qtdIPSM*ipsm + qtdUNI*uni + qtdCASU*casu; //total de $ com fernando
        double totalEdu = qtdPART*part; //total de $ com eduardo
        double totalPlan = qtdMESES*plano; //total de $ do plano
        double totalImp = totalFer*0.275;
        double totalGer = totalFer + totalEdu; //total de $ com os 2
        double finalEdu = totalGer/2 - totalPlan - totalImp/2; //total de $ que deve ficar com eduardo depois da divisão e descontando o plano + impostos
        double finalFer = totalGer/2 + totalPlan + totalImp/2; //total de $ que deve ficar com fernando depois da divisão e adicionando o plano + impostos
        
        
        setDetalhes("--> VALOR COM EDUARDO:\n"
                + qtdPART +" Particulares. Total: "+ totalEdu+"\n ----------------- \n"
                + "--> VALOR COM FERNANDO:\n\n"
                + qtdIPSM+" IPSM. Total: "+ (int) Math.ceil(qtdIPSM*ipsm) +";\n"
                + qtdUNI +" UNIMED. Total:  "+ (int) Math.ceil(qtdUNI*uni) +";\n"
                + qtdCASU +" CASU. Total: "+ (int) Math.ceil(qtdCASU*casu) +".\n\n"
                + "Total: " + (int) Math.ceil(totalFer) + ".\n\nImpostos: "+ (int) Math.ceil(totalImp) +" ("+ (int) Math.ceil(totalImp/2) +" pra cada)\n"
                + "-----------------\n"
                + "VALOR TOTAL: \n"+(int) Math.ceil(totalGer)+ " ("+ (int) Math.ceil(totalGer/2) +" pra cada)\n\n"
                + "VALOR DO PLANO: \n"
                + qtdMESES+" mes(es) ("+totalPlan+")\n\n"
                + "-----------------\n"
                + "Valor final de Eduardo = Parte de Eduardo ("+ (int) Math.ceil(totalGer/2) + ") "
                + " - plano de saúde ("+ totalPlan +") - impostos ("+ (int) Math.ceil(totalImp/2) +") = " + ((int) Math.ceil(finalEdu)) + "\n"
                + "         Diferença: " + ((int) Math.ceil(finalEdu - totalEdu)) + "\n"
                + "Valor final de Fernando = Parte de Fernando: ("+ (int) Math.ceil(totalGer/2) + ") "
                + " + plano de saúde ("+ totalPlan +") + impostos ("+ (int) Math.ceil(totalImp/2) +") = " + ((int) Math.ceil(finalFer)) + "\n"
                + "         Diferença: " + ((int) Math.ceil(finalFer - totalFer)) + "\n");
             
        
        if (finalEdu - totalEdu < 0){ //se o valor que ele deve ficar for menor do que o que tá com ele, ele tem que passar a diferença pra fernando
            setResultado("Particulares: "+ qtdPART+ "\n"
                + "IPSM: "+ qtdIPSM+ "\n"
                + "UNIMED: "+ qtdUNI+ "\n"
                + "Casu: "+ qtdCASU+ "\n"
                + "Meses do plano de saúde: "+ qtdMESES+ "\n\n"
                + "Valor a ser  passado pra Fernando: " + ((int) Math.ceil(finalEdu-totalEdu))*-1);
            return;
        }
        if (finalEdu - totalEdu > 0){ //se o valor que ele deve ficar for maior do que o que tá com ele, fernando tem que passar a diferença pra ele
            setResultado("Particulares: "+ qtdPART+ "\n"
                + "IPSM: "+ qtdIPSM+ "\n"
                + "UNIMED: "+ qtdUNI+ "\n"
                + "Casu: "+ qtdCASU+ "\n"
                + "Meses do plano de saúde: "+ qtdMESES+ "\n\n"
                + "Valor a ser  passado pra Eduardo: " + ((int) Math.ceil(finalEdu-totalEdu)));
            return;

        }
        else {
            setResultado("Particulares: "+ qtdPART+ "\n"
                + "IPSM: "+ qtdIPSM+ "\n"
                + "UNIMED: "+ qtdUNI+ "\n"
                + "Casu: "+ qtdCASU+ "\n"
                + "Meses do plano de saúde: "+ qtdMESES+ "\n\n"
                + "Nenhum valor deve ser passado");
            return;

        }
        
        
        
    }

}

